[Game]
tts_enabled = true

[Gemini]
api_key = 
[groq]
api_key = 
[modelscope]
api_key = 
[aliyuncs]
api_key = 
[glm4]
api_key = 
[sparkmax]
api_key = 
service_id = 
api_base = 
[cohere]
api_key = 
[mistral]
api_key = 
model = 
[hunyuan]
api_key = 

# [代理设置]
# 可选的网络请求代理设置。
# 如果需要，请取消注释并设置您的代理地址和端口。
HTTP_PROXY=http://127.0.0.1:10808
HTTPS_PROXY=http://127.0.0.1:10808

[Ollama]
# 本地运行的 Ollama 通常不需要特定的 API 密钥。
# 如果您的 Ollama 实例是托管的并且需要身份验证，请根据需要进行配置。
# api_base = http://localhost:11434 # 例如，本地运行时的地址